[[main]]
  name = "Home"
  url = ""
  weight = -110

#[[main]]
#  name = "Archives"
#  url = "post/rich-content/"
#  weight = -109

# Submenus are done this way: parent -> identifier
#[[main]]
#  name = "Links"
#  identifier = "Links"
#  weight = -108
#[[main]]
#  parent = "Links"
#  name = "LinkedIn"
#  url = "https://www.linkedin.com/"
#[[main]]
#  parent = "Links"
#  name = "X"
#  url = "https://x.com/"

[[main]]
  name = "About"
  url = "about/"
  weight = -107


[[main]]
  name = "Examinations"
  identifier = "examinations"
  weight = -106
  url = "/examinations/"

[[main]]
  parent = "examinations"
  name = "BPSC"
  url = "examinations/bpsc/"
  identifier = "bpsc"
  weight = -105

[[main]]
  parent = "examinations"
  name = "UPPSC"
  url = "examinations/uppsc/"
  identifier = "uppsc"
  weight = -104

[[main]]
  parent     = "bpsc"
  name       = "Preliminary Examination"
  url        = "examinations/bpsc/preliminary-examination/"
  weight     = -103

[[main]]
  parent     = "uppsc"
  name       = "Preliminary Examination"
  url        = "examinations/uppsc/preliminary-examination/"
  weight     = -102




# social menu links

[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/himanshushekharpande/Mainaa-v3"
[[social]]
  name = "X"
  weight = 2
  url = "https://x.com/mainaa_news"
[[social]]
  name = "linkedin"
  weight = 3
  url = "https://www.linkedin.com/in/#"
[[social]]
  name = "rss"
  weight = 4
  url = "index.xml"

# other supported social links
# name = "youtube"
# url = "https://www.youtube.com/#"
# name = "facebook"
# url = "https://facebook.com/#"
# name = "instagram"
# url = "https://instagram.com/#"
# name = "stackoverflow"
# url = "https://stackoverflow.com/#"
# name = "gitlab"
# url = "https://gitlab.com/#"
# name = "discord"
# url = "https://discord.gg/#"
# name = "bluesky"
# url = "https://bsky.app/profile/#"